services:
    runner:
      image: tcardonne/github-runner:latest
      restart: unless-stopped
      environment:
        RUNNER_NAME: ${RUNNER_NAME}
        RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
        RUNNER_TOKEN: ${RUNNER_TOKEN}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock